### ISSUE TITLE
sample app crashes on second attempt

### ISSUE THREAD

**Issue by Johnett** [afollestad/inline-activity-result#1]
Hello Aidan,
I know it's too early to report an issue if this is irrelevant please ignore it. There is a bug in the sample project included in this library. 

**Affected Device(s):**
Nexus 5X with Android 7.1.1(in AVD)
Samsung Galaxy S6 edge plus with Android 7.0

**Describe the Bug:**
   App crashes when I try to launch the second activity for the second time(without closing the   app after first attempt).

**To Reproduce:**

    Step 1-> Open up the sample app and press on the "launch second activity" button.
    Step 2-> Step 1 will open an activity enter something in the Edittext box and press "Success" or
                  "Failure" button this will finish the activity and show the result as a Toast.                              
    Step 3-> When I try to do Step 1 again the app crashes.
                   Then try to remove any of the last two.

**Logcat:**
  
```
535-8535/com.afollestad.inlineactivityresultsample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.afollestad.inlineactivityresultsample, PID: 8535
    java.lang.IllegalStateException: There is already a pending request for request code 20
        at com.afollestad.inlineactivityresult.InlineActivityResult.schedule(InlineActivityResult.kt:34)
        at com.afollestad.inlineactivityresult.ActivitiesKt.startActivityForResult(Activities.kt:56)
        at com.afollestad.inlineactivityresultsample.MainActivity$onCreate$1.onClick(MainActivity.kt:25)
        at android.view.View.performClick(View.java:5637)
        at android.view.View$PerformClick.run(View.java:22429)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Screenshots -----**

![attempt 1](https://user-images.githubusercontent.com/25472210/56716402-e72fdc80-6757-11e9-9847-3e4c49e0d1aa.png)

![attempt 2](https://user-images.githubusercontent.com/25472210/56716412-ee56ea80-6757-11e9-894f-4359d98ca962.png)

**Comment by Johnett** [comment]
Hello Aidan,
There is another bug similar to this one but doesn't fit into the normal use case, And it's hard to reproduce.
I will add the details below.

**Affected Device(s):** 
Nexus 5X with Android 7.1.1(in AVD)
Samsung Galaxy S6 edge plus with Android 7.0

**Screenshots:**
![report 2](https://user-images.githubusercontent.com/25472210/56784906-8adcc380-6810-11e9-80bb-f86de148be76.png)

**To Reproduce:**
Place the mouse pointer on the marked spot(please see the screenshot). And click the buttons(first activity "launch second activity button" and second activity "success" button) continuously(don't mind the activity change(button 1 launch second activity and button 2 finish second activity)). In AVD it's too easy to reproduce but in the real device, it's very hard.

<img src="https://user-images.githubusercontent.com/25472210/56785537-49014c80-6813-11e9-8f55-261c15e87e48.gif" alt="specimen" width="250" height="450">


**Logcat:**
```
java.lang.IllegalStateException: There is already a pending request for requestCode 69.
        at com.afollestad.inlineactivityresult.internal.InlineActivityResult.schedule(InlineActivityResult.kt:34)
        at com.afollestad.inlineactivityresult.ActivitiesKt.startActivityForResult(Activities.kt:56)
        at com.afollestad.inlineactivityresultsample.MainActivity$onCreate$1.onClick(MainActivity.kt:27)
        at android.view.View.performClick(View.java:5637)
        at android.view.View$PerformClick.run(View.java:22429)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by afollestad** [comment]
Oh, that's expected because the request code isn't changed. Clicks would probably be denounced at the app level or different request codes would need to be used each time.

**Comment by Johnett** [comment]
Thank you for the explanation.
